plugin.json

Eric will be getting those links set up to redirect to the documentation once that is ready.
https://mattermost.atlassian.net/browse/MM-14501

MM-14501 Update help text links to point to redirects

---

server/hooks.go
server/utils.go

This makes it so that Surveybot responds to written feedback and sends those responses to Segment.
This PR is based on https://github.com/mattermost/mattermost-plugin-nps/pull/9. Changes specific to it can be seen here: https://github.com/mattermost/mattermost-plugin-nps/compare/mm-14691...mm14340
https://mattermost.atlassian.net/browse/MM-14340

MM-14340 Send written feedback to Segment 

---

server/api.go
server/hooks.go
server/survey.go
server/survey_templates.go
server/utils.go

Fixes a few minor bugs including:
1. Not all Surveybot posts were marked with the "BOT" tag
2. The link in the system admin DM was broken
3. Survey and notification DMs were not sent on login until the user refreshed

Various bug fixes

---

server/api.go
webapp/package-lock.json
webapp/package.json
webapp/src/action_types.js
webapp/src/actions.js
webapp/src/client.js
webapp/src/components/confirm_feedback_modal/confirm_feedback_modal.jsx
webapp/src/components/confirm_feedback_modal/index.js
webapp/src/components/root.jsx
webapp/src/hooks.js
webapp/src/index.js
webapp/src/reducers.js
webapp/src/selectors.js
webapp/webpack.config.js

Requires https://github.com/mattermost/mattermost-webapp/pull/2526 to be merged to add the new plugin hook used for this.
The modal still needs some additional styling, but I wanted to get the logic submitted and reviewed first.
https://mattermost.atlassian.net/browse/MM-14341

MM-14341 Add confirmation modal when sending written feedback

---

.circleci/config.yml

- the context need to go in another section otherwise will not work as expected

fix context in circleci

---

plugin.json
server/activate.go

I merged https://github.com/mattermost/mattermost-plugin-nps/pull/13 to quickly :man_facepalming:.
This needs to be merged after the server version has been bumped, which will happen in a few days.

Use min_server_version instead of selfwritten solution

---

server/activate.go

The current version refuses to start if it loses track of the Surveybot account somehow

Attempt to use existing Surveybot account if it already exists

---

server/activate.go
server/hooks.go
server/plugin.go

This updates it to match the text that we were including in the channel header

Properly set Surveybot's description

---

plugin.json
server/activate.go
server/hooks.go
server/survey.go
server/survey_templates.go
server/utils.go

This PR makes the following changes:
1. Update some text and fix a typo
2. Fix the fact that the bot user ID isn't reloaded properly because it was being serialized as a json string and then deserialized as a regular string
3. Removes the `from_webhook` prop from bot posts so that the profile picture is correct when EnablePostIconOverride is enabled

Minor fixes and tweaks

---

webapp/src/client.js

This is to fix the warnings about XMLHttpRequest being deprecated.
https://mattermost.atlassian.net/browse/MM-14804

MM-14804 Set CSRF token from cookie

---

webapp/package-lock.json
webapp/package.json
webapp/src/components/survey_post/index.js
webapp/src/components/survey_post/score.jsx
webapp/src/components/survey_post/survey_post.jsx
webapp/src/constants.js
webapp/src/index.js

This makes it so that the posts from Surveybot that ask the user for an NPS score look much nicer, as per the spec. There are some issues on smaller screen sizes, but I've filed a followup ticket to address that.
https://mattermost.atlassian.net/browse/MM-14743

MM-14743 Add custom post for NPS score

---

server/survey_templates.go

fix the link to the new url for admin_console > integrations

[MM-15755] fix link to admin console > integrations

---

server/hooks.go
server/hooks_test.go

This is to clean up some garbage feedback that we've been getting.
https://mattermost.atlassian.net/browse/MM-16682

MM-16682 Stop Surveybot from responding to system messages

---

webapp/src/components/survey_post/score.jsx
webapp/src/components/survey_post/survey_post.jsx

**Ticket**
https://mattermost.atlassian.net/browse/MM-16609

MM-16609- Updating bg for nps rating

---

webapp/package-lock.json
webapp/package.json

Update results from npm audit fix

npm audit fix

---

plugin.json
server/manifest.go
webapp/src/manifest.js

Update NPS plugin version
https://mattermost.atlassian.net/browse/MM-23827

[MM-23827] - Update NPS version

---

server/api.go
server/api_test.go
server/survey.go
server/survey_test.go
server/telemetry.go
webapp/src/components/survey_post/survey_post.jsx

implemented per-user disable
https://mattermost.atlassian.net/browse/MM-25887

MM-25887  Ability to disable NPS surveys on a user level

---

server/activate.go

Close telemetry client after deactivation
None

Close client after deactivation

---

plugin.json
server/manifest.go
webapp/src/manifest.js

Update NPS plugin version
https://mattermost.atlassian.net/browse/MM-28520

MM-28520-Update NPS plugin version

---

plugin.json
server/manifest.go
webapp/src/manifest.js

Add `release_notes_url`
https://github.com/mattermost/mattermost-marketplace/pull/121#discussion_r491996882

Add release_notes_url

---

.circleci/config.yml
.golangci.yml
Makefile
build/manifest/main.go
go.mod
go.sum
server/activate.go
server/activate_test.go
server/api.go
server/api_test.go
server/plugin.go
server/survey.go
server/survey_templates.go
server/welcome.go
server/welcome_test.go

For the feature:
- Sends a DM after 7 days to ask new users a feedback
- Save the date at which the feature above has been added to the server to not request feedback from users created more than 7 days before this feature becomes active.
- Change the 21 days waiting time to 45 days
- Changed the time between requests to 90days to 180days
Other ~ sorry for the noise during the review:
- Changed the CircleCI file to use golang 1.18 (was stuck at 1.16 with the plugin-ci orb)
- Updated some deprecated code (`io/ioutil` was deprecated since go 1.16)
This version is modified to simplify QA:
- The Welcome message is sent 7 minutes after a new account is created instead of 7 days.
- The waiting time is 45 minutes instead of 45 days
- Change the delay between requests from 180days to 180minutes …

[MM-45718+MM-46367] Add welcome feedback post + change 21 days waiting time to 45

---

plugin.json

Bump version to 1.3.0
https://mattermost.atlassian.net/browse/MM-47696
* acb35bbf45a6fd28fd4d07b064ecbd7187f06f04 Create .gitpod.yml (#89)
* 260316d9c6c55de73bed2036f35d66f9aacd4db0 [MM-45718+MM-46367] Add welcome feedback post + change 21 days waiting time to 45 (#90)
* 80ad633aa09042141b2736911d92d7977db15df4 [MM-47546] Update plugin from the starter template (#93)
* 6955a1428c1ec780ca8fec8064910281216cb0ec MM-46440: Update logo (#92)
* d34beb6ceb6474a5954acc5298437f2d8f542ec9 [MM-46818] Ask for email on confirmation popin (#94)
* e4346c78f5392ba2dfdc35b4d55168c28b39d4d2 Automate backend manifest read (#96)
* (TBD) Bump version to 1.3.0 (#97)
* 031d3ce85c2e18c28626e61264ad021f21d31eab Fix linter errors (#91)

Bump version to 1.3.0

---

plugin.json

Bump version to v1.3.1
https://mattermost.atlassian.net/browse/MM-49087
* 984828bc71de7d2559c95209e9f1cd9266c0a170 plugin don't report feedback since 1.3.0 (#98)

Bump version to 1.3.1

---

README.md

Creating this PR to address @wiggin77 remark on the new changes in the README ~ It's also a good chance for anyone to leave feedback on the documentation addition from https://github.com/mattermost/mattermost-plugin-nps/commit/b9e7b488abf1f6e860779c83ae930d25729f5139
N/A OSF

Feedback on documentation

---

webapp/src/index.js

Fixed casing `Give feedback` menu entry for consistency. 
https://mattermost.atlassian.net/browse/MM-44173

Fixed help menu title casing

---

plugin.json

Minor release to pre-package with v8.0
**Fixes:**
https://github.com/mattermost/mattermost-plugin-nps/pull/103 - Fix Rudder key env vars 
https://github.com/mattermost/mattermost-plugin-nps/pull/105 - Typo fix in Help menu
https://mattermost.atlassian.net/browse/MM-53114

Bumped version to 1.3.2

---

webapp/src/components/confirm_feedback_modal/confirm_feedback_modal.jsx

Fixed missing email in the feedback telemetry - we need to actually pass it for it to reach the server. 
https://mattermost.atlassian.net/browse/MM-54753

Fixed missing email in feedback telemetry

---

plugin.json

Minor release to pre-package with v9.2
Fixes:
https://github.com/mattermost/mattermost-plugin-nps/pull/107 - Fix missing email field in feedback telemetry
https://mattermost.atlassian.net/browse/MM-54753

Bumped version to 1.3.3
