mattermost/mattermost-plugin-nps

server/api.go, server/survey.go, server/survey_test.go
This timestamp was supposed to be set for each user when they gave their 0 to 10 feedback score, but I forgot to actually add that logic.
=> Fix AnsweredAt not being set

server/hooks.go
Using the hook lets us set the header regardless of who how the DM channel was created.
https://mattermost.atlassian.net/browse/MM-14691
=> MM-14691 Add channel header message for SurveyBot

server/api.go, server/survey.go
Previously, answered survey posts would just be replaced by plain text
but that made it a bit difficult to see that Surveybot asked for written feedback. We're changing it to keep the message attachment box so that the transition is a bit less jarring and hopefully make it more obvious that there was a followup question
=> Update answered survey posts based on UX feedback

plugin.json, server/activate.go
Use https://developers.mattermost.com/extend/plugins/manifest-reference/#min_server_version instead of self written solution.
This needs to be merged after the server version has been bumped, which will happen in a few days.
=> Use min_server_version instead of selfwritten solution

server/segment.go
As discussed [here](https://community-daily.mattermost.com/core/pl/1jsmygcgciyzi8mo7dcriqmkga), it's okay to have this included in the repository. The reason the server repository doesn't include its Segment key is primarily because it gets used a lot more, and we didn't want to get a ton of junk data from test builds
=> Add actual Segment key

server/activate.go, server/survey.go, server/test_commands.go
The `nps-test` command will be controlled by a constant, so the test build will have to be manually generated. The other refactoring is just to give me some easy constants when changing some times to allow for QA to test within a reasonable amount of time.
https://mattermost.atlassian.net/browse/MM-14553
=> MM-14553 Add nps-test command and refactor for test build

webapp/src/client.js
This is needed for the test build, but since I'm compiling that manually, this doesn't need to go into the version shipped in 5.10
=> Use plugin ID from manifest for API calls

server/activate.go, server/configuration.go, server/plugin.go, server/survey.go, server/survey_test.go
I managed to forget to implement a key part of the plugin settings somehow. This fixes the name of the EnableSurvey setting and ensures that survey-related functions are only ran when that setting is true.
=> MM-14786 Properly implement Enable NPS Survey setting

server/activate.go, server/activate_test.go, server/api.go, server/configuration.go, server/main.go, server/plugin.go, server/survey.go, server/utils.go
This is based on https://github.com/mattermost/mattermost-plugin-nps/pull/25, so the changes specific to it are here: https://github.com/mattermost/mattermost-plugin-nps/compare/hh-disable-survey...hh-race.
Due to the lack of synchronization logic in the plugin API, we're adding a short delay before code paths that are likely to cause race conditions to reduce the chance that a race condition occurs in an HA environment where two plugin instances try to either schedule surveys or send survey DMs at the same time. While the delays are up to 2 minutes on a server upgrade or 1 second when checking if a survey DM needs to be sent, those should be significantly longer than either of those operations take, so the chances of two processes hitting each other there should be much lower when …
=>  Add a random delay before handling events to mitigate against race conditions

server/Gopkg.lock, server/Gopkg.toml, server/activate.go, server/activate_test.go, server/api.go, server/api_test.go, server/configuration.go, server/configuration_test.go, server/hooks.go, server/hooks_test.go, server/plugin.go, server/segment.go, server/segment_test.go, server/survey.go, server/survey_test.go, server/upgrade.go, server/upgrade_test.go, server/utils.go, server/utils_test.go
This does a lot of refactoring and some cleanup while adding a lot of unit tests.
Major changes:
- I split the KV store entries that track when an upgrade occurred from when a survey is scheduled so that it's easier to reason about how the code should work. The previous version gave me a lot of problems because I kept making mistakes when I was trying to write utilities to help QA test the plugin.
- I added a lot of unit tests to everything. The tests aren't amazing because of limitations of the mocking framework (everything has to be mocked by hand), but refactoring some of the logic into helper functions has helped that somewhat.
Minor changes:
- I renamed everything like `userId` to `userID` for consistency
- I removed the dependency on `github.com/blang/semver` because we weren't …
=> MM-14854 Refactor plugin and add a bunch of unit tests

server/Gopkg.lock, server/Gopkg.toml, server/api.go, server/api_test.go, server/survey.go, server/survey_test.go
Uses the new functionality added in https://github.com/mattermost/mattermost-server/pull/10659 to save the previous score submitted by the user so that they can change the score after submitting it.
As per the spec, a change in a user's score is sent to Segment exactly the same as if it was the first time that the user selected something. Surveybot only thanks the user for their feedback when they first select a score though.
https://mattermost.atlassian.net/browse/MM-14742
=> MM-14742 Add ability for user to change their submitted score

server/Gopkg.lock, server/Gopkg.toml, server/activate.go, server/activate_test.go, server/api.go, server/api_test.go, server/lock.go, server/lock_test.go, server/plugin.go, server/survey.go, server/survey_test.go
This replaces the locks that were part of the `Plugin` struct as well as the hacky delays meant to mitigate against having two plugin instances modifying user state at the same time.
A few important things to note:
1. There's two different types of locking used: one lock for checking whether or not a survey needs to be scheduled and an arbitrary number of per-user locks for checking their survey state and seeing if they need to receive any DMs.
2. Since there's no way to make entries expire if they were added using `KVCompareAndSet`, I made it so that when the plugin starts up, it will check for any locks that were acquired over an hour ago, just in case a previous plugin instance died while holding a lock. I thought about using `KVSetWithExpiry` after the `KVCompareAndSet` to accomplish …
=> MM-14876 Use KVCompareAndSet to add locking for HA

server/segment.go, server/segment_test.go
The name `user_id` conflicts with Segment's "user ID" which is actually the server's diagnostic ID. Using a different name for the user ID prevents that from being overwritten. This matches the naming convention of some of our other diagnostics as well
https://mattermost.atlassian.net/browse/MM-15745
=> MM-15745 Rename user_id field in Segment to user_actual_id

Makefile, webapp/.eslintrc.json, webapp/__mocks__/react-bootstrap.js, webapp/babel.config.js, webapp/jest.config.js, webapp/package-lock.json, webapp/package.json, webapp/src/action_types.js, webapp/src/actions.js, webapp/src/components/survey_post/index.js, webapp/src/components/survey_post/score.jsx, webapp/src/components/survey_post/survey_post.jsx, webapp/src/index.js, webapp/src/index.test.js, webapp/src/reducers.js, webapp/src/selectors.js, webapp/test_setup.js, webapp/webpack.config.js
This uses the new, smaller design for the score post in the RHS and when there's not enough space in the centre channel because the RHS is open. Mobile view still falls back to the dropdown menu like before.
https://mattermost.atlassian.net/browse/MM-15342
=> MM-15342 Use a smaller score post for certain screen sizes

webapp/src/client.js
The `document.cookie` has whitespace after each cookie value, so the `startsWith` would sometimes fail to identify the correct cookie
https://mattermost.atlassian.net/browse/MM-14804
=> MM-14804 Trim cookie values when looking for the CSRF token 

plugin.json
Followup to the much earlier fix to make it so that the help text for plugins could support Markdown. I added the ability for the plugin help text to open links in a new tab, but I forgot to actually implement it.
https://mattermost.atlassian.net/browse/MM-8647
https://github.com/mattermost/mattermost-webapp/pull/2912
=> MM-8647 Change system console links to open in a new tab

plugin.json, server/api_test.go, server/survey.go, server/survey_test.go
[MM-10982](https://mattermost.atlassian.net/browse/MM-10982) introduced support for relative post integration action URLs, reducing the overhead on plugins when building the actions and simultaneously enabling SiteURL-agnostic action handling with a plugin. Leverage this functionality in the NPS plugin for new posts. Existing posts will continue to use the absolute URL embedded in the post metadata.
Note that this functionality requires 5.14.0, now reflected in plugin.json.
=> MM-16611: leverage relative action URLs

README.md, plugin.json, server/activate.go, server/lock.go, server/segment.go, server/survey.go, server/survey_templates.go, webapp/package.json
We've renamed Net Promoter Score surveys to user satisfaction surveys since that's a less technical term for them. The internal name of the plugin isn't changing.
=> MM-16285 Rename NPS surveys to user satisfaction surveys

webapp/jest.config.js, webapp/src/actions.js, webapp/src/actions.test.js
This stops a harmless JS error that happens when the app is opened but the user hasn't logged in yet.
https://mattermost.atlassian.net/browse/MM-17585
=> MM-15785 Only call connected API if user is logged in

server/activate.go, server/activate_test.go
We always get this error/debug in the logs:
```
{"level":"debug","ts":1604739700.2061086,"caller":"mlog/sugar.go:15","msg":"Failed to create Surveybot. Attempting to find existing one.","plugin_id":"com.mattermost.nps","err":"SqlUserStore.Save: An account with that username already exists., user_id=yjnohck5wtnmdqyqihzkxe51fr, pq: duplicate key value violates unique constraint \"users_username_key\""}
```
this PR change the order and try to get the user first and if get an error we try to create it
none
=> try to get the bot first and if not found try to create it

server/manifest.go, server/survey.go, server/telemetry.go
QoL improvement for maintainer
The `plugin.go` file at the project's root reads `plugin.json` automatically, but we were not using it.
With this change, we would have to only edit `plugin.json` to change the plugin version (instead of plugin.json+`/server/manifest.go`)
N/A
=> Automate backend manifest read

build/custom.mk
While upgrading the Makefile I did not realize that the LDFLAGS variable is not used anymore. As a consequence, during CI we were not injecting the prod rudder key. This PR inject the LDFLAGS into the GO_BUILD_FLAGS so that we compile the project with the flags set.
**Note**: This is 1.3.1 worthy and we might want to tag this ASAP after merge.
@stevemudie QA steps are, as always with NPS, super fun :D 
1. Create a cloud server on mattermost with `/cloud create YOURNAME-test-cloud-nps --image mattermost/mm-ee-cloud --version cloud-2022-12-01-1`
1. login as sysadmin (credentials provided by the cloud bot)
1. Send a feedback to the feedbackbot
1. Go to the server log (System Console > Server Logs). You should find a line containing `Failed to read writeKey from header`. This validates that …
=> [MM-49064] plugin don't report feedback since 1.3.0
